# Generated by Django 4.0 on 2021-12-21 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_alter_player_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restapi.team'),
        ),
    ]
